# Etapa 1: build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copia tudo da solution para dentro do container
COPY . .

# Vai até o projeto principal (API)
WORKDIR /app/src/HousesPapon.API

# Restaura os pacotes
RUN dotnet restore

# Publica o projeto em modo Release para uma pasta limpa
RUN dotnet publish -c Release -o /app/publish

# Etapa 2: runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Copia os arquivos publicados da etapa de build
COPY --from=build /app/publish .

# Expõe a porta padrão do ASP.NET Core
EXPOSE 80

# Comando de inicialização
ENTRYPOINT ["dotnet", "HousesPapon.API.dll"]
